apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitlab-runner
rules:
- apiGroups: 
    - ""
    - "extensions"
    - "apps"
    - "networking.k8s.io" 
  resources:
    - "secrets"
    - "configmaps"
    - "deployments"
    - "replicasets"
    - "pods"
    - "pods/attach"
    - "pods/exec"
    - "service"
    - "namespaces"
  verbs:
    - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitlab-runner
roleRef:
  kind: ClusterRole 
  name: gitlab-runner
  apiGroup: ""

subjects:
- kind: ServiceAccount
  name: default
  namespace: k8s-gitlab-runner
  apiGroup: ""
