apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: topics
data:
  DATABASE_URL: mongodb://topicsuser:password@mongo-svc:27017/TopicstoreDb?authSource=admin
  DATABASE_NAME: TopicstoreDb
  HOST: 0.0.0.0
  PORT: '5000'