apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-topic-api
  namespace: topics
spec:
  selector:
    matchLabels:
      app: backend-topic-api
  template:
    metadata:
      labels:
        app: backend-topic-api
    spec:
      containers:
      - name: backend-topic-api
        image: yoandevelop/backend-topic-api:${{ github.sha }}
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DATABASE_URL

        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DATABASE_NAME

        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: HOST

        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: PORT
        resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-topic-svc
  namespace: topics
spec:
  type: NodePort
  selector:
    app: backend-topic-api
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
