apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-express-config
  namespace: topics
data:
  ME_CONFIG_MONGODB_ADMINUSERNAME: topicsuser
  ME_CONFIG_MONGODB_ADMINPASSWORD: password
  ME_CONFIG_MONGODB_URL: mongodb://topicsuser:password@mongo-svc:27017/TopicstoreDb?authSource=admin
  ME_CONFIG_BASICAUTH : 'false'